library(devtools)
use_r("univariate")
use_r("tools")
use_r("parse")
use_r("descTab")
use_r("bivariate")
use_r("Classes")
use_gpl_license()

use_package("stringi")
use_package("dplyr")
use_package("purrr")
use_package("tibble")
use_package("kableExtra")

use_package("stats")
use_package("methods")
use_package("tidyr")

document()
devtools::check()

build(".")
library(rhub)
rhub::check()
